### ISSUE TITLE
Enhancement Request: Is it possible to add the spacewalk-client-repo version as an attribute?

### ISSUE THREAD

**Issue by helhindi** [philicious/spacewalk-client-chef#7]
Hi philicious

Thanks for the awesome spacewalk cookbooks.

I was wondering if it would be possible for you to define the spacewalk-client-repo version number as an attribute?
spacewalk-client/recipes/rhel.rb Line 4:
From:
source "#{node['spacewalk']['rhel']['base_url']}/#{platform_major}/#{arch}/spacewalk-client-repo-2.2-1.el#{platform_major}.noarch.rpm"
To (an example):
source "#{node['spacewalk']['rhel']['base_url']}/#{platform_major}/#{arch}/spacewalk-client-repo-#{node['spacewalk']['client']['repo_ver']}.el#{platform_major}.noarch.rpm"

We are currently using your cookbook as base with a wrapper and we often need to hard code the version number to the most current version.

This will enable us to define the client version (If of course, the cookbook does not explicitly require a version number to stay as is....)

Many thanks,
helhindi

**Comment by philicious** [comment]
Good to know this cookbook is also helping/used by someone else :D

Yes I can make that change tomorrow. Its kinda related to the old&merged PR for making the base_url modifiable https://github.com/philicious/spacewalk-client-chef/pull/1

**Comment by philicious** [comment]
also any PRs are always welcome

**Comment by helhindi** [comment]
Many thanks for your swift response and help. Good to know that PRs are welcome :)

**Comment by philicious** [comment]
@helhindi I added your request with https://github.com/philicious/spacewalk-client-chef/commit/faedfacf972193a6a3b6ff927f45c4232b43a193 = v0.1.12

its tested to work, however could you please verify its doing what you need before I push the new version to chef supermarket?

**Comment by helhindi** [comment]
@philicious - Thanks ever so much for your help.
I have tested the cookbook and it is is working perfectly.
I am very pleased with the addition of the client repo version attribute.
Great work!

**Comment by philicious** [comment]
@helhindi i pushed to supermarket now. so you can get it from there now also https://supermarket.chef.io/cookbooks/spacewalk-client
