### ISSUE TITLE
Client installation without Internet access

### ISSUE THREAD

**Issue by rosario-mattera** [philicious/spacewalk-client-chef#8]
Currently the script needs to have Internet access to download some packages. How can I install the client without Internet access?Should I modify the script connecting to a local repository for the download?

**Comment by philicious** [comment]
@rosario-mattera I see several methods here:
- you could provision the required packages onto the machine, just as the few packages mentioned in the README and modify the cookbook so it will pick them up locally
- you could bake all required packages into the image that you use to install these machines
- you could setup a repo in that LAN which contains the packages and have these machines use it as a source
- Spacewalk can do kickstarts/provisioning, see https://fedorahosted.org/spacewalk/wiki/ManagingFedoraSystems#ProvisioningClients
- you could give these nodes internet access via a proxy / NAT gateway

**Comment by rosario-mattera** [comment]
OK. That's basically the approach. I was hoping something already implemented was available.

Thank you.
